# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: openeuicc.keystore
          fileDir: openeuicc
          encodedString: ${{ secrets.SIGNINGKEYBASE64 }}
          
      - name: Decode Secret Signing Configuration
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: keystore.properties
          fileDir: openeuicc
          encodedString: ${{ secrets.OPENEUICC_SIGNING_CONFIG }}

      - name: Add Keystore Path to Config
        run:  |
          sudo chmod 666 openeuicc/keystore.properties
          sudo echo "storeFile=${{ github.workspace }}/openeuicc/openeuicc.keystore" >> ${{ github.workspace }}/keystore.properties
      
      - name: Build kernelsu-module-openeuicc
        run: bash build.sh

      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: module.zip
          asset_name: module.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ github.event.head_commit.message }}
